# Generated by Django 5.2.13 on 2026-04-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.PositiveIntegerField(default=400, help_text='Poids en grammes (utilisé pour les frais de port)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
