# Generated by Django 5.2.13 on 2026-04-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_weight_g_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bullet_1',
            field=models.TextField(blank=True, help_text='Premier argument de vente (accroche principale)', verbose_name='Argument 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_2',
            field=models.TextField(blank=True, verbose_name='Argument 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_3',
            field=models.TextField(blank=True, verbose_name='Argument 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='bullet_4',
            field=models.TextField(blank=True, verbose_name='Argument 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, help_text='Ex: Coupe fourreau, fermeture eclair invisible au dos, entierement doublee', verbose_name='Details de coupe'),
        ),
        migrations.AddField(
            model_name='product',
            name='expert_tip',
            field=models.TextField(blank=True, verbose_name="Conseil d'expert"),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.TextField(blank=True, help_text='Ex: Crepe de polyester, legèrement extensible', verbose_name='Matiere'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_chest',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Aisselle a aisselle (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_hips',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Hanches (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur totale (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_shoulder',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Epaule a epaule (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_sleeve',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Longueur des manches (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='mix_match_tips',
            field=models.TextField(blank=True, help_text='3 idees de tenues (une par ligne)', verbose_name='Idees Mix & Match'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_recommendation',
            field=models.CharField(blank=True, help_text='Ex: Convient a un 8 ajuste', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='size_tag',
            field=models.CharField(blank=True, help_text="Taille indiquee sur l'etiquette (ex: 10, L/G, 8P)", max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmee'), ('shipped', 'Expediee'), ('delivered', 'Livree'), ('cancelled', 'Annulee')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.JSONField(blank=True, default=list, help_text='Palette de couleurs (codes hex)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new_with_tags', 'Neuf avec etiquette'), ('excellent', 'Excellent etat'), ('very_good', 'Tres bon etat'), ('good', 'Bon etat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Texte long de presentation', verbose_name='Description produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('unique', 'Taille unique'), ('autre', 'Autre (voir taille indiquee)')], help_text='Taille standard (pour les filtres)', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_g',
            field=models.PositiveIntegerField(default=400, help_text='Poids en grammes (frais de port)'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
            options={
                'verbose_name': 'Sous-categorie',
                'verbose_name_plural': 'Sous-categories',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.subcategory'),
        ),
    ]
