# Generated by Django 5.2.13 on 2026-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_bullet_1_product_bullet_2_product_bullet_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Pourcentage (%)'), ('fixed', 'Montant fixe ($)')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Valeur de la reduction (% ou $)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Laisser vide = illimite', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum du panier', max_digits=8)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Laisser vide = pas d'expiration", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
